# Generated by Django 5.1 on 2026-09-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['payroll_period'], name='payroll_pay_payroll_295b49_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='payroll_pay_status_465a76_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'payroll_period'], name='payroll_pay_employe_28acc8_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['employee', 'status'], name='payroll_sal_employe_b1c35d_idx'),
        ),
    ]
