# Generated by Django 6.0.8 on 2026-09-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll_payroll_pay_payroll_295b49_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='daily_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='daily_salary_formula',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
