# Generated by Django 6.0.8 on 2026-09-19 08:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payroll_daily_salary_payroll_daily_salary_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='absent_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='attendance_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payroll',
            name='leave_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
