# Generated by Django 6.0.8 on 2026-09-19 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_absent_days_payroll_attendance_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='holiday_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5),
        ),
    ]
