# Generated by Django 6.0.8 on 2026-09-19 11:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_branch'),
        ('payroll', '0005_payroll_holiday_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='unpaid_leave_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.CreateModel(
            name='DeductionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('absent', 'Absent'), ('unpaid_leave', 'Leave Unpaid'), ('late', 'Late'), ('early_leave', 'Early Leave'), ('custom', 'Custom / Other')], max_length=30)),
                ('condition_unit', models.CharField(choices=[('days', 'Days'), ('hours', 'Hours'), ('times', 'Times (Occurrences)')], default='days', max_length=20)),
                ('operator', models.CharField(choices=[('always', 'Per Unit (Always Apply)'), ('lte', '≤ Less than or equal to'), ('lt', '< Less than'), ('gte', '≥ Greater than or equal to'), ('gt', '> Greater than'), ('between', 'Between'), ('eq', '= Equal to')], default='always', max_length=20)),
                ('threshold_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('threshold_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calc_type', models.CharField(choices=[('percent_daily', '% of Salary / Day'), ('percent_hourly', '% of Salary / Hour'), ('percent_monthly', '% of Monthly Salary'), ('fixed_per_unit', 'Fixed Amount per Unit ($)'), ('fixed_flat', 'Fixed Flat Amount ($)')], max_length=30)),
                ('rate_or_amount', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 100 for 100%) or Fixed dollar amount', max_digits=10)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Lower number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_rules', to='companies.company')),
            ],
            options={
                'ordering': ['category', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('condition_unit', models.CharField(default='days', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rate_or_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_items', to='payroll.payroll')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_items', to='payroll.deductionrule')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
