import io
import datetime
import html
from decimal import Decimal

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from reportlab.lib.pagesizes import letter, A4, landscape
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


# ==============================================================================
# REPORTLAB HELPERS & NUMBERED CANVAS
# ==============================================================================

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and print total page count 'Page X of Y'
    along with running header and footer lines.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor('#64748B'))

        # Running Footer
        footer_y = 25
        page_w, page_h = self._pagesize

        # Footer divider line
        self.setStrokeColor(colors.HexColor('#E2E8F0'))
        self.setLineWidth(0.75)
        self.line(36, footer_y + 12, page_w - 36, footer_y + 12)

        # Left footer: System & Confidentiality
        self.drawString(36, footer_y, "CONFIDENTIAL — Generated by Payroll MGM System")

        # Right footer: Page number
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(page_w - 36, footer_y, page_str)

        # Center footer: Timestamp
        now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.drawCentredString(page_w / 2.0, footer_y, f"Generated on {now_str}")

        self.restoreState()


def get_pdf_styles():
    styles = getSampleStyleSheet()
    
    # Custom styles
    if 'ReportTitle' not in styles:
        styles.add(ParagraphStyle(
            name='ReportTitle',
            fontName='Helvetica-Bold',
            fontSize=18,
            leading=22,
            textColor=colors.HexColor('#0F172A'),
            spaceAfter=4,
        ))
    if 'ReportSubtitle' not in styles:
        styles.add(ParagraphStyle(
            name='ReportSubtitle',
            fontName='Helvetica',
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor('#64748B'),
            spaceAfter=12,
        ))
    if 'CompanyName' not in styles:
        styles.add(ParagraphStyle(
            name='CompanyName',
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=15,
            textColor=colors.HexColor('#1E3A8A'),
        ))
    if 'SectionHeader' not in styles:
        styles.add(ParagraphStyle(
            name='SectionHeader',
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=16,
            textColor=colors.HexColor('#1E293B'),
            spaceBefore=10,
            spaceAfter=6,
        ))
    if 'TableHeader' not in styles:
        styles.add(ParagraphStyle(
            name='TableHeader',
            fontName='Helvetica-Bold',
            fontSize=8.5,
            leading=11,
            textColor=colors.white,
            alignment=0,
        ))
    if 'TableHeaderRight' not in styles:
        styles.add(ParagraphStyle(
            name='TableHeaderRight',
            fontName='Helvetica-Bold',
            fontSize=8.5,
            leading=11,
            textColor=colors.white,
            alignment=2,
        ))
    if 'TableCell' not in styles:
        styles.add(ParagraphStyle(
            name='TableCell',
            fontName='Helvetica',
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor('#334155'),
            alignment=0,
        ))
    if 'TableCellBold' not in styles:
        styles.add(ParagraphStyle(
            name='TableCellBold',
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor('#0F172A'),
            alignment=0,
        ))
    if 'TableCellRight' not in styles:
        styles.add(ParagraphStyle(
            name='TableCellRight',
            fontName='Helvetica',
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor('#334155'),
            alignment=2,
        ))
    if 'TableCellRightBold' not in styles:
        styles.add(ParagraphStyle(
            name='TableCellRightBold',
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor('#0F172A'),
            alignment=2,
        ))
    if 'TableCellCenter' not in styles:
        styles.add(ParagraphStyle(
            name='TableCellCenter',
            fontName='Helvetica',
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor('#334155'),
            alignment=1,
        ))
    if 'BadgeSuccess' not in styles:
        styles.add(ParagraphStyle(
            name='BadgeSuccess',
            fontName='Helvetica-Bold',
            fontSize=7.5,
            leading=9.5,
            textColor=colors.HexColor('#059669'),
            alignment=1,
        ))
    if 'BadgeWarning' not in styles:
        styles.add(ParagraphStyle(
            name='BadgeWarning',
            fontName='Helvetica-Bold',
            fontSize=7.5,
            leading=9.5,
            textColor=colors.HexColor('#D97706'),
            alignment=1,
        ))
    if 'BadgeDanger' not in styles:
        styles.add(ParagraphStyle(
            name='BadgeDanger',
            fontName='Helvetica-Bold',
            fontSize=7.5,
            leading=9.5,
            textColor=colors.HexColor('#DC2626'),
            alignment=1,
        ))
    return styles


def build_signature_block(page_width=500):
    """Generates standard executive authorization sign-off block."""
    styles = get_pdf_styles()
    sig_data = [
        [
            Paragraph("<b>Prepared By:</b>", styles['TableCellBold']),
            Paragraph("<b>Verified By HR:</b>", styles['TableCellBold']),
            Paragraph("<b>Approved By Management:</b>", styles['TableCellBold'])
        ],
        [
            Paragraph("<br/><br/>_______________________<br/>Signature & Date", styles['TableCell']),
            Paragraph("<br/><br/>_______________________<br/>Signature & Date", styles['TableCell']),
            Paragraph("<br/><br/>_______________________<br/>Signature & Date", styles['TableCell'])
        ]
    ]
    col_w = page_width / 3.0
    t = Table(sig_data, colWidths=[col_w, col_w, col_w])
    t.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
    ]))
    return KeepTogether([Spacer(1, 20), t])


# ==============================================================================
# OPENPYXL STYLES & BUILDER
# ==============================================================================

class ExcelTheme:
    NAVY_HEADER_FILL = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
    SUBHEADER_FILL = PatternFill(start_color="F1F5F9", end_color="F1F5F9", fill_type="solid")
    ZEBRA_FILL = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")
    TOTALS_FILL = PatternFill(start_color="E2E8F0", end_color="E2E8F0", fill_type="solid")
    SUCCESS_FILL = PatternFill(start_color="DCFCE7", end_color="DCFCE7", fill_type="solid")
    WARNING_FILL = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")
    DANGER_FILL = PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid")

    FONT_TITLE = Font(name="Calibri", size=16, bold=True, color="0F172A")
    FONT_SUBTITLE = Font(name="Calibri", size=10, italic=True, color="64748B")
    FONT_HEADER = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    FONT_BOLD = Font(name="Calibri", size=10, bold=True, color="0F172A")
    FONT_REGULAR = Font(name="Calibri", size=10, color="1E293B")
    FONT_TOTAL = Font(name="Calibri", size=11, bold=True, color="0F172A")

    BORDER_THIN = Border(
        left=Side(style='thin', color='CBD5E1'),
        right=Side(style='thin', color='CBD5E1'),
        top=Side(style='thin', color='CBD5E1'),
        bottom=Side(style='thin', color='CBD5E1')
    )
    BORDER_TOTAL = Border(
        left=Side(style='thin', color='CBD5E1'),
        right=Side(style='thin', color='CBD5E1'),
        top=Side(style='thin', color='0F172A'),
        bottom=Side(style='double', color='0F172A')
    )

    ALIGN_LEFT = Alignment(horizontal="left", vertical="center")
    ALIGN_CENTER = Alignment(horizontal="center", vertical="center")
    ALIGN_RIGHT = Alignment(horizontal="right", vertical="center")
    ALIGN_HEADER = Alignment(horizontal="center", vertical="center", wrap_text=True)

    FMT_CURRENCY = '$#,##0.00'
    FMT_INTEGER = '#,##0'
    FMT_PERCENT = '0.0%'
    FMT_DATE = 'yyyy-mm-dd'
    FMT_TIME = 'hh:mm'


def auto_fit_columns(ws, min_width=12, padding=4):
    """Dynamically sizes Excel columns so text is never truncated."""
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            val = str(cell.value or '')
            if '\n' in val:
                lines = val.split('\n')
                line_len = max(len(l) for l in lines) if lines else 0
                max_len = max(max_len, line_len)
            else:
                max_len = max(max_len, len(val))
        ws.column_dimensions[col_letter].width = max(max_len + padding, min_width)


def add_excel_header_block(ws, company_name, report_title, subtitle, generated_by="System", max_col=7):
    """Renders a corporate banner and metadata card on rows 1 to 4."""
    # Row 1: Company Title
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=max_col)
    c1 = ws.cell(row=1, column=1, value=(company_name or "Payroll Management System").upper())
    c1.font = Font(name="Calibri", size=11, bold=True, color="1E3A8A")
    c1.alignment = ExcelTheme.ALIGN_LEFT
    ws.row_dimensions[1].height = 18

    # Row 2: Report Title
    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=max_col)
    c2 = ws.cell(row=2, column=1, value=report_title)
    c2.font = ExcelTheme.FONT_TITLE
    c2.alignment = ExcelTheme.ALIGN_LEFT
    ws.row_dimensions[2].height = 24

    # Row 3: Subtitle / Scope
    ws.merge_cells(start_row=3, start_column=1, end_row=3, end_column=max_col)
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    meta_text = f"{subtitle} | Generated on: {now_str} | Generated by: {generated_by}"
    c3 = ws.cell(row=3, column=1, value=meta_text)
    c3.font = ExcelTheme.FONT_SUBTITLE
    c3.alignment = ExcelTheme.ALIGN_LEFT
    ws.row_dimensions[3].height = 18

    # Row 4: Spacer
    ws.row_dimensions[4].height = 8


# ==============================================================================
# 1. DAILY ATTENDANCE REPORT (EXCEL & PDF)
# ==============================================================================

def generate_daily_attendance_excel(report_date, attendances, stats, company_name="Payroll MGM", generated_by="Admin"):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = f"Daily_{report_date.strftime('%Y%m%d')}"
    ws.views.sheetView[0].showGridLines = True

    add_excel_header_block(
        ws,
        company_name=company_name,
        report_title=f"Daily HR & Attendance Report",
        subtitle=f"Date: {report_date.strftime('%B %d, %Y (%A)')}",
        generated_by=generated_by,
        max_col=7
    )

    # Summary KPI Block (Rows 5 to 7)
    kpis = [
        ("Total Active Employees", stats.get('total_employees', 0), ExcelTheme.FMT_INTEGER),
        ("Present", stats.get('present_count', 0), ExcelTheme.FMT_INTEGER),
        ("Late Check-ins", stats.get('late_count', 0), ExcelTheme.FMT_INTEGER),
        ("Absent", stats.get('absent_count', 0), ExcelTheme.FMT_INTEGER),
        ("Early Leave", stats.get('early_leave_count', 0), ExcelTheme.FMT_INTEGER),
        ("Overtime", stats.get('overtime_count', 0), ExcelTheme.FMT_INTEGER),
        ("Attendance Rate", stats.get('attendance_rate', 0) / 100.0, ExcelTheme.FMT_PERCENT)
    ]

    # KPI Headers
    for c_idx, (kpi_label, val, fmt) in enumerate(kpis, start=1):
        cell_lbl = ws.cell(row=5, column=c_idx, value=kpi_label)
        cell_lbl.font = Font(name="Calibri", size=9, bold=True, color="475569")
        cell_lbl.fill = ExcelTheme.SUBHEADER_FILL
        cell_lbl.alignment = ExcelTheme.ALIGN_CENTER
        cell_lbl.border = ExcelTheme.BORDER_THIN

        cell_val = ws.cell(row=6, column=c_idx, value=val)
        cell_val.font = Font(name="Calibri", size=13, bold=True, color="0F172A")
        cell_val.fill = ExcelTheme.SUBHEADER_FILL
        cell_val.alignment = ExcelTheme.ALIGN_CENTER
        cell_val.border = ExcelTheme.BORDER_THIN
        cell_val.number_format = fmt

    ws.row_dimensions[5].height = 18
    ws.row_dimensions[6].height = 24
    ws.row_dimensions[7].height = 10

    # Table Headers (Row 8)
    headers = ["#", "Employee Code", "Employee Name", "Department", "Position", "Check In", "Check Out", "Working Hours", "Status"]
    ws.row_dimensions[8].height = 26

    for c_idx, h in enumerate(headers, start=1):
        c = ws.cell(row=8, column=c_idx, value=h)
        c.font = ExcelTheme.FONT_HEADER
        c.fill = ExcelTheme.NAVY_HEADER_FILL
        c.alignment = ExcelTheme.ALIGN_HEADER
        c.border = ExcelTheme.BORDER_THIN

    # Table Data (Row 9+)
    curr_row = 9
    for idx, a in enumerate(attendances, start=1):
        emp = a.employee
        cin = a.check_in.strftime("%H:%M") if a.check_in else "-"
        cout = a.check_out.strftime("%H:%M") if a.check_out else "-"
        hours_str = str(a.working_hours).split('.')[0] if a.working_hours else "-"
        status_lbl = a.get_status_display()

        row_vals = [
            (idx, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (emp.employee_code, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (f"{emp.first_name} {emp.last_name}".strip(), ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_BOLD, None),
            (emp.department.name if emp.department else "-", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_REGULAR, None),
            (emp.position.name if emp.position else "-", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_REGULAR, None),
            (cin, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (cout, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (hours_str, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (status_lbl, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_BOLD, None),
        ]

        zebra = ExcelTheme.ZEBRA_FILL if curr_row % 2 == 0 else PatternFill(fill_type=None)
        ws.row_dimensions[curr_row].height = 20

        for c_idx, (v, align, font, fmt) in enumerate(row_vals, start=1):
            cell = ws.cell(row=curr_row, column=c_idx, value=v)
            cell.font = font
            cell.alignment = align
            cell.border = ExcelTheme.BORDER_THIN
            if c_idx == 9:
                if a.status == 'present':
                    cell.fill = ExcelTheme.SUCCESS_FILL
                elif a.status == 'late':
                    cell.fill = ExcelTheme.WARNING_FILL
                elif a.status == 'absent':
                    cell.fill = ExcelTheme.DANGER_FILL
                else:
                    cell.fill = zebra
            else:
                cell.fill = zebra

            if fmt:
                cell.number_format = fmt

        curr_row += 1

    if not attendances:
        ws.merge_cells(start_row=curr_row, start_column=1, end_row=curr_row, end_column=len(headers))
        empty_c = ws.cell(row=curr_row, column=1, value="No attendance records found for this date.")
        empty_c.font = ExcelTheme.FONT_SUBTITLE
        empty_c.alignment = ExcelTheme.ALIGN_CENTER
        empty_c.border = ExcelTheme.BORDER_THIN
        ws.row_dimensions[curr_row].height = 25
        curr_row += 1

    ws.freeze_panes = 'A9'
    auto_fit_columns(ws)

    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()


def generate_daily_attendance_pdf(report_date, attendances, stats, company_name="Payroll MGM", generated_by="Admin"):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(letter),
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=45
    )

    styles = get_pdf_styles()
    story = []

    # Title & Metadata Header
    story.append(Paragraph(html.escape(company_name.upper()), styles['CompanyName']))
    story.append(Paragraph(f"Daily Attendance & HR Report", styles['ReportTitle']))
    date_str = report_date.strftime("%B %d, %Y (%A)")
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    story.append(Paragraph(f"Report Date: <b>{date_str}</b> &nbsp;|&nbsp; Generated: {now_str} &nbsp;|&nbsp; Prepared by: {html.escape(generated_by)}", styles['ReportSubtitle']))

    # KPI Summary Tiles
    kpi_data = [
        [
            Paragraph("<b>Active Workforce</b>", styles['TableCellCenter']),
            Paragraph("<b>Present</b>", styles['TableCellCenter']),
            Paragraph("<b>Late</b>", styles['TableCellCenter']),
            Paragraph("<b>Absent</b>", styles['TableCellCenter']),
            Paragraph("<b>Early Leave</b>", styles['TableCellCenter']),
            Paragraph("<b>Overtime</b>", styles['TableCellCenter']),
            Paragraph("<b>Attendance Rate</b>", styles['TableCellCenter']),
        ],
        [
            Paragraph(f"<font size=12><b>{stats.get('total_employees', 0)}</b></font>", styles['TableCellCenter']),
            Paragraph(f"<font size=12 color='#059669'><b>{stats.get('present_count', 0)}</b></font>", styles['TableCellCenter']),
            Paragraph(f"<font size=12 color='#D97706'><b>{stats.get('late_count', 0)}</b></font>", styles['TableCellCenter']),
            Paragraph(f"<font size=12 color='#DC2626'><b>{stats.get('absent_count', 0)}</b></font>", styles['TableCellCenter']),
            Paragraph(f"<font size=12 color='#2563EB'><b>{stats.get('early_leave_count', 0)}</b></font>", styles['TableCellCenter']),
            Paragraph(f"<font size=12 color='#7C3AED'><b>{stats.get('overtime_count', 0)}</b></font>", styles['TableCellCenter']),
            Paragraph(f"<font size=12 color='#059669'><b>{stats.get('attendance_rate', 0):.1f}%</b></font>", styles['TableCellCenter']),
        ]
    ]
    t_kpi = Table(kpi_data, colWidths=[105] * 7)
    t_kpi.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(t_kpi)
    story.append(Spacer(1, 14))

    # Main Table
    story.append(Paragraph("<b>Employee Attendance Activity Logs</b>", styles['SectionHeader']))

    table_data = [
        [
            Paragraph("#", styles['TableHeader']),
            Paragraph("Code", styles['TableHeader']),
            Paragraph("Employee Name", styles['TableHeader']),
            Paragraph("Department", styles['TableHeader']),
            Paragraph("Position", styles['TableHeader']),
            Paragraph("Check In", styles['TableHeader']),
            Paragraph("Check Out", styles['TableHeader']),
            Paragraph("Hours", styles['TableHeader']),
            Paragraph("Status", styles['TableHeader']),
        ]
    ]

    for idx, a in enumerate(attendances, start=1):
        emp = a.employee
        cin = a.check_in.strftime("%H:%M") if a.check_in else "-"
        cout = a.check_out.strftime("%H:%M") if a.check_out else "-"
        hours_str = str(a.working_hours).split('.')[0] if a.working_hours else "-"
        
        status_style = styles['BadgeSuccess'] if a.status == 'present' else (
            styles['BadgeWarning'] if a.status == 'late' else (
                styles['BadgeDanger'] if a.status == 'absent' else styles['TableCellCenter']
            )
        )

        table_data.append([
            Paragraph(str(idx), styles['TableCellCenter']),
            Paragraph(html.escape(emp.employee_code), styles['TableCell']),
            Paragraph(f"<b>{html.escape(emp.first_name)} {html.escape(emp.last_name)}</b>", styles['TableCell']),
            Paragraph(html.escape(emp.department.name if emp.department else "-"), styles['TableCell']),
            Paragraph(html.escape(emp.position.name if emp.position else "-"), styles['TableCell']),
            Paragraph(cin, styles['TableCellCenter']),
            Paragraph(cout, styles['TableCellCenter']),
            Paragraph(hours_str, styles['TableCellCenter']),
            Paragraph(html.escape(a.get_status_display()), status_style),
        ])

    if not attendances:
        table_data.append([
            Paragraph("No attendance activity recorded for this date.", styles['TableCellCenter']),
            "", "", "", "", "", "", "", ""
        ])

    # Table Column Widths for Landscape Letter (792 - 72 = 720pt)
    col_widths = [30, 60, 160, 110, 110, 60, 60, 60, 70]
    t = Table(table_data, colWidths=col_widths, repeatRows=1)
    
    t_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
    ]
    if not attendances:
        t_style.append(('SPAN', (0, 1), (-1, 1)))

    t.setStyle(TableStyle(t_style))
    story.append(t)

    # Sign-off block
    story.append(build_signature_block(page_width=720))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()


# ==============================================================================
# 2. EXECUTIVE SUMMARY REPORT (EXCEL & PDF)
# ==============================================================================

def generate_summary_report_excel(period_str, payrolls, dept_stats, summary_stats, company_name="Payroll MGM", generated_by="Admin"):
    wb = openpyxl.Workbook()
    
    # Sheet 1: Executive Overview & Department Distribution
    ws1 = wb.active
    ws1.title = "Executive Summary"
    ws1.views.sheetView[0].showGridLines = True

    add_excel_header_block(
        ws1,
        company_name=company_name,
        report_title="Executive Payroll & HR Summary Report",
        subtitle=f"Period: {period_str or 'All Periods'}",
        generated_by=generated_by,
        max_col=6
    )

    # Financial Summary Tiles
    tiles = [
        ("Total Workforce", summary_stats.get('total_employees', 0), ExcelTheme.FMT_INTEGER),
        ("Active Employees", summary_stats.get('active_employees', 0), ExcelTheme.FMT_INTEGER),
        ("Total Gross Payroll", summary_stats.get('total_gross', 0), ExcelTheme.FMT_CURRENCY),
        ("Total Deductions", summary_stats.get('total_deductions', 0), ExcelTheme.FMT_CURRENCY),
        ("Net Payroll Paid", summary_stats.get('total_net', 0), ExcelTheme.FMT_CURRENCY),
        ("Average Net Salary", summary_stats.get('avg_salary', 0), ExcelTheme.FMT_CURRENCY),
    ]

    for c_idx, (lbl, val, fmt) in enumerate(tiles, start=1):
        c_lbl = ws1.cell(row=5, column=c_idx, value=lbl)
        c_lbl.font = Font(name="Calibri", size=9, bold=True, color="475569")
        c_lbl.fill = ExcelTheme.SUBHEADER_FILL
        c_lbl.alignment = ExcelTheme.ALIGN_CENTER
        c_lbl.border = ExcelTheme.BORDER_THIN

        c_val = ws1.cell(row=6, column=c_idx, value=val)
        c_val.font = Font(name="Calibri", size=13, bold=True, color="0F172A")
        c_val.fill = ExcelTheme.SUBHEADER_FILL
        c_val.alignment = ExcelTheme.ALIGN_CENTER
        c_val.border = ExcelTheme.BORDER_THIN
        c_val.number_format = fmt

    ws1.row_dimensions[5].height = 18
    ws1.row_dimensions[6].height = 24
    ws1.row_dimensions[7].height = 12

    # Section 1: Department Payroll Distribution Table
    ws1.cell(row=8, column=1, value="Department Payroll & Workforce Distribution").font = ExcelTheme.FONT_TITLE
    ws1.row_dimensions[8].height = 22

    dept_headers = ["Department", "Headcount", "Total Gross Salary", "Total Deductions", "Total Net Salary", "% Share"]
    ws1.row_dimensions[9].height = 24
    for c_idx, h in enumerate(dept_headers, start=1):
        c = ws1.cell(row=9, column=c_idx, value=h)
        c.font = ExcelTheme.FONT_HEADER
        c.fill = ExcelTheme.NAVY_HEADER_FILL
        c.alignment = ExcelTheme.ALIGN_HEADER
        c.border = ExcelTheme.BORDER_THIN

    row_idx = 10
    total_net_sum = float(summary_stats.get('total_net', 0)) or 1.0

    for d in dept_stats:
        net_val = float(d.get('total_net', 0))
        share = net_val / total_net_sum if total_net_sum > 0 else 0

        ws1.row_dimensions[row_idx].height = 20
        vals = [
            (d.get('name', 'Unassigned'), ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_BOLD, None),
            (d.get('count', 0), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_INTEGER),
            (float(d.get('total_gross', 0)), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(d.get('total_deductions', 0)), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (net_val, ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_BOLD, ExcelTheme.FMT_CURRENCY),
            (share, ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_PERCENT),
        ]
        zebra = ExcelTheme.ZEBRA_FILL if row_idx % 2 == 0 else PatternFill(fill_type=None)
        for c_idx, (v, align, font, fmt) in enumerate(vals, start=1):
            cell = ws1.cell(row=row_idx, column=c_idx, value=v)
            cell.font = font
            cell.alignment = align
            cell.border = ExcelTheme.BORDER_THIN
            cell.fill = zebra
            if fmt:
                cell.number_format = fmt
        row_idx += 1

    # Totals Row for Depts
    ws1.row_dimensions[row_idx].height = 22
    tot_vals = [
        ("Total / Grand Summary", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_TOTAL, None),
        (f"=SUM(B10:B{row_idx-1})" if row_idx > 10 else 0, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_INTEGER),
        (f"=SUM(C10:C{row_idx-1})" if row_idx > 10 else 0, ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
        (f"=SUM(D10:D{row_idx-1})" if row_idx > 10 else 0, ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
        (f"=SUM(E10:E{row_idx-1})" if row_idx > 10 else 0, ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
        (1.0, ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_PERCENT),
    ]
    for c_idx, (v, align, font, fmt) in enumerate(tot_vals, start=1):
        cell = ws1.cell(row=row_idx, column=c_idx, value=v)
        cell.font = font
        cell.alignment = align
        cell.border = ExcelTheme.BORDER_TOTAL
        cell.fill = ExcelTheme.TOTALS_FILL
        if fmt:
            cell.number_format = fmt

    auto_fit_columns(ws1)

    # Sheet 2: Payroll Register Items
    ws2 = wb.create_sheet(title="Payroll Register")
    ws2.views.sheetView[0].showGridLines = True

    add_excel_header_block(
        ws2,
        company_name=company_name,
        report_title="Period Payroll Detailed Register",
        subtitle=f"Period: {period_str or 'All Periods'}",
        generated_by=generated_by,
        max_col=10
    )

    p_headers = ["#", "Period", "Employee Code", "Employee Name", "Department", "Basic Salary", "Gross Salary", "Total Deductions", "Net Salary", "Status"]
    ws2.row_dimensions[5].height = 24

    for c_idx, h in enumerate(p_headers, start=1):
        c = ws2.cell(row=5, column=c_idx, value=h)
        c.font = ExcelTheme.FONT_HEADER
        c.fill = ExcelTheme.NAVY_HEADER_FILL
        c.alignment = ExcelTheme.ALIGN_HEADER
        c.border = ExcelTheme.BORDER_THIN

    p_row = 6
    for idx, p in enumerate(payrolls, start=1):
        emp = p.employee
        ws2.row_dimensions[p_row].height = 20
        row_vals = [
            (idx, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (p.payroll_period.strftime("%b %Y"), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (emp.employee_code, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (f"{emp.first_name} {emp.last_name}".strip(), ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_BOLD, None),
            (emp.department.name if emp.department else "-", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_REGULAR, None),
            (float(p.basic_salary), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.gross_salary), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.total_deduction), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.net_salary), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_BOLD, ExcelTheme.FMT_CURRENCY),
            (p.get_status_display(), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_BOLD, None),
        ]
        zebra = ExcelTheme.ZEBRA_FILL if p_row % 2 == 0 else PatternFill(fill_type=None)
        for c_idx, (v, align, font, fmt) in enumerate(row_vals, start=1):
            cell = ws2.cell(row=p_row, column=c_idx, value=v)
            cell.font = font
            cell.alignment = align
            cell.border = ExcelTheme.BORDER_THIN
            cell.fill = zebra
            if fmt:
                cell.number_format = fmt
        p_row += 1

    if payrolls:
        # Totals
        ws2.row_dimensions[p_row].height = 22
        tots = [
            ("Grand Total", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_TOTAL, None),
            ("", ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_TOTAL, None),
            ("", ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_TOTAL, None),
            ("", ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_TOTAL, None),
            ("", ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_TOTAL, None),
            (f"=SUM(F6:F{p_row-1})", ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
            (f"=SUM(G6:G{p_row-1})", ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
            (f"=SUM(H6:H{p_row-1})", ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
            (f"=SUM(I6:I{p_row-1})", ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
            ("", ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_TOTAL, None),
        ]
        for c_idx, (v, align, font, fmt) in enumerate(tots, start=1):
            cell = ws2.cell(row=p_row, column=c_idx, value=v)
            cell.font = font
            cell.alignment = align
            cell.border = ExcelTheme.BORDER_TOTAL
            cell.fill = ExcelTheme.TOTALS_FILL
            if fmt:
                cell.number_format = fmt

    ws2.freeze_panes = 'A6'
    auto_fit_columns(ws2)

    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()


def generate_summary_report_pdf(period_str, payrolls, dept_stats, summary_stats, company_name="Payroll MGM", generated_by="Admin"):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=45
    )

    styles = get_pdf_styles()
    story = []

    # Title & Metadata
    story.append(Paragraph(html.escape(company_name.upper()), styles['CompanyName']))
    story.append(Paragraph("Executive Payroll & HR Summary", styles['ReportTitle']))
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    story.append(Paragraph(f"Period: <b>{html.escape(period_str or 'All Periods')}</b> &nbsp;|&nbsp; Generated: {now_str} &nbsp;|&nbsp; Prepared by: {html.escape(generated_by)}", styles['ReportSubtitle']))

    # KPI Matrix (2 rows x 3 columns)
    kpis = [
        [
            Paragraph("<b>Total Workforce</b>", styles['TableCellCenter']),
            Paragraph("<b>Total Gross Payroll</b>", styles['TableCellCenter']),
            Paragraph("<b>Total Net Disbursed</b>", styles['TableCellCenter']),
        ],
        [
            Paragraph(f"<font size=12><b>{summary_stats.get('total_employees', 0)}</b></font>", styles['TableCellCenter']),
            Paragraph(f"<font size=12 color='#1E3A8A'><b>${summary_stats.get('total_gross', 0):,.2f}</b></font>", styles['TableCellCenter']),
            Paragraph(f"<font size=12 color='#059669'><b>${summary_stats.get('total_net', 0):,.2f}</b></font>", styles['TableCellCenter']),
        ],
        [
            Paragraph("<b>Active Workforce</b>", styles['TableCellCenter']),
            Paragraph("<b>Total Deductions</b>", styles['TableCellCenter']),
            Paragraph("<b>Average Net Salary</b>", styles['TableCellCenter']),
        ],
        [
            Paragraph(f"<font size=12 color='#059669'><b>{summary_stats.get('active_employees', 0)}</b></font>", styles['TableCellCenter']),
            Paragraph(f"<font size=12 color='#DC2626'><b>${summary_stats.get('total_deductions', 0):,.2f}</b></font>", styles['TableCellCenter']),
            Paragraph(f"<font size=12 color='#0F172A'><b>${summary_stats.get('avg_salary', 0):,.2f}</b></font>", styles['TableCellCenter']),
        ]
    ]
    t_kpi = Table(kpis, colWidths=[180, 180, 180])
    t_kpi.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t_kpi)
    story.append(Spacer(1, 14))

    # Department Breakdown Table
    story.append(Paragraph("<b>Department Payroll & Workforce Distribution</b>", styles['SectionHeader']))
    dept_table = [
        [
            Paragraph("Department", styles['TableHeader']),
            Paragraph("Headcount", styles['TableHeader']),
            Paragraph("Gross Salary", styles['TableHeaderRight']),
            Paragraph("Deductions", styles['TableHeaderRight']),
            Paragraph("Net Salary", styles['TableHeaderRight']),
            Paragraph("% Share", styles['TableHeaderRight']),
        ]
    ]

    total_net = float(summary_stats.get('total_net', 0)) or 1.0
    for d in dept_stats:
        d_net = float(d.get('total_net', 0))
        share = (d_net / total_net * 100.0) if total_net > 0 else 0
        dept_table.append([
            Paragraph(f"<b>{html.escape(d.get('name', 'Unassigned'))}</b>", styles['TableCellBold']),
            Paragraph(str(d.get('count', 0)), styles['TableCellCenter']),
            Paragraph(f"${d.get('total_gross', 0):,.2f}", styles['TableCellRight']),
            Paragraph(f"${d.get('total_deductions', 0):,.2f}", styles['TableCellRight']),
            Paragraph(f"<b>${d_net:,.2f}</b>", styles['TableCellRightBold']),
            Paragraph(f"{share:.1f}%", styles['TableCellRight']),
        ])

    dept_table.append([
        Paragraph("<b>Total Grand Summary</b>", styles['TableCellBold']),
        Paragraph(f"<b>{summary_stats.get('total_employees', 0)}</b>", styles['TableCellCenter']),
        Paragraph(f"<b>${summary_stats.get('total_gross', 0):,.2f}</b>", styles['TableCellRightBold']),
        Paragraph(f"<b>${summary_stats.get('total_deductions', 0):,.2f}</b>", styles['TableCellRightBold']),
        Paragraph(f"<b>${summary_stats.get('total_net', 0):,.2f}</b>", styles['TableCellRightBold']),
        Paragraph("<b>100.0%</b>", styles['TableCellRightBold']),
    ])

    t_dept = Table(dept_table, colWidths=[140, 60, 90, 80, 100, 70])
    t_dept.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#E2E8F0')),
        ('LINEABOVE', (0, -1), (-1, -1), 1, colors.HexColor('#0F172A')),
        ('LINEBELOW', (0, -1), (-1, -1), 1.5, colors.HexColor('#0F172A')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#F8FAFC')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(t_dept)
    story.append(Spacer(1, 14))

    # Recent Payroll Ledger Snippet (Top 10)
    story.append(Paragraph("<b>Payroll Ledger Summary</b>", styles['SectionHeader']))
    p_table = [
        [
            Paragraph("Period", styles['TableHeader']),
            Paragraph("Employee", styles['TableHeader']),
            Paragraph("Department", styles['TableHeader']),
            Paragraph("Gross", styles['TableHeaderRight']),
            Paragraph("Deductions", styles['TableHeaderRight']),
            Paragraph("Net Salary", styles['TableHeaderRight']),
            Paragraph("Status", styles['TableHeader']),
        ]
    ]
    for p in payrolls[:15]:
        p_table.append([
            Paragraph(p.payroll_period.strftime("%b %Y"), styles['TableCell']),
            Paragraph(f"{html.escape(p.employee.first_name)} {html.escape(p.employee.last_name)}", styles['TableCellBold']),
            Paragraph(html.escape(p.employee.department.name if p.employee.department else "-"), styles['TableCell']),
            Paragraph(f"${p.gross_salary:,.2f}", styles['TableCellRight']),
            Paragraph(f"-${p.total_deduction:,.2f}", styles['TableCellRight']),
            Paragraph(f"<b>${p.net_salary:,.2f}</b>", styles['TableCellRightBold']),
            Paragraph(html.escape(p.get_status_display()), styles['TableCellCenter']),
        ])
    if not payrolls:
        p_table.append([
            Paragraph("No payroll records found for this period.", styles['TableCellCenter']),
            "", "", "", "", "", ""
        ])

    t_p = Table(p_table, colWidths=[65, 125, 95, 75, 75, 80, 55], repeatRows=1)
    p_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]
    if not payrolls:
        p_style.append(('SPAN', (0, 1), (-1, 1)))
    t_p.setStyle(TableStyle(p_style))
    story.append(t_p)

    story.append(build_signature_block(page_width=540))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()


# ==============================================================================
# 3. DETAIL REPORT (MULTI-TAB EXCEL & LANDSCAPE PDF)
# ==============================================================================

def generate_detail_report_excel(employees, payrolls, attendances, company_name="Payroll MGM", generated_by="Admin"):
    wb = openpyxl.Workbook()

    # Sheet 1: Employee Master Roster
    ws1 = wb.active
    ws1.title = "Employee Master Roster"
    ws1.views.sheetView[0].showGridLines = True

    add_excel_header_block(
        ws1,
        company_name=company_name,
        report_title="Employee Master Roster Ledger",
        subtitle=f"Total Records: {len(employees)}",
        generated_by=generated_by,
        max_col=10
    )

    e_headers = ["#", "Code", "First Name", "Last Name", "Gender", "Email", "Phone", "Department", "Position", "Basic Salary", "Join Date", "Status"]
    ws1.row_dimensions[5].height = 24

    for c_idx, h in enumerate(e_headers, start=1):
        c = ws1.cell(row=5, column=c_idx, value=h)
        c.font = ExcelTheme.FONT_HEADER
        c.fill = ExcelTheme.NAVY_HEADER_FILL
        c.alignment = ExcelTheme.ALIGN_HEADER
        c.border = ExcelTheme.BORDER_THIN

    for r_idx, emp in enumerate(employees, start=6):
        ws1.row_dimensions[r_idx].height = 20
        row_vals = [
            (r_idx - 5, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (emp.employee_code, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (emp.first_name, ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_BOLD, None),
            (emp.last_name, ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_BOLD, None),
            (emp.get_gender_display(), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (emp.email, ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_REGULAR, None),
            (emp.phone or "-", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_REGULAR, None),
            (emp.department.name if emp.department else "-", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_REGULAR, None),
            (emp.position.name if emp.position else "-", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_REGULAR, None),
            (float(emp.basic_salary), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_BOLD, ExcelTheme.FMT_CURRENCY),
            (emp.join_date.strftime("%Y-%m-%d"), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (emp.get_status_display(), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_BOLD, None),
        ]
        zebra = ExcelTheme.ZEBRA_FILL if r_idx % 2 == 0 else PatternFill(fill_type=None)
        for c_idx, (v, align, font, fmt) in enumerate(row_vals, start=1):
            cell = ws1.cell(row=r_idx, column=c_idx, value=v)
            cell.font = font
            cell.alignment = align
            cell.border = ExcelTheme.BORDER_THIN
            cell.fill = zebra
            if fmt:
                cell.number_format = fmt

    ws1.freeze_panes = 'A6'
    auto_fit_columns(ws1)

    # Sheet 2: Payroll Register
    ws2 = wb.create_sheet(title="Payroll Register")
    ws2.views.sheetView[0].showGridLines = True

    add_excel_header_block(
        ws2,
        company_name=company_name,
        report_title="Payroll Master Register",
        subtitle=f"Total Records: {len(payrolls)}",
        generated_by=generated_by,
        max_col=11
    )

    pr_headers = ["#", "Period", "Employee Code", "Employee Name", "Department", "Basic Salary", "Allowance", "Overtime", "Bonus", "Gross Salary", "Tax", "NSSF", "Other Ded.", "Total Ded.", "Net Salary", "Status"]
    ws2.row_dimensions[5].height = 24

    for c_idx, h in enumerate(pr_headers, start=1):
        c = ws2.cell(row=5, column=c_idx, value=h)
        c.font = ExcelTheme.FONT_HEADER
        c.fill = ExcelTheme.NAVY_HEADER_FILL
        c.alignment = ExcelTheme.ALIGN_HEADER
        c.border = ExcelTheme.BORDER_THIN

    for r_idx, p in enumerate(payrolls, start=6):
        emp = p.employee
        ws2.row_dimensions[r_idx].height = 20
        row_vals = [
            (r_idx - 5, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (p.payroll_period.strftime("%Y-%m"), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (emp.employee_code, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (f"{emp.first_name} {emp.last_name}".strip(), ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_BOLD, None),
            (emp.department.name if emp.department else "-", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_REGULAR, None),
            (float(p.basic_salary), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.allowance), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.overtime), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.bonus), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.gross_salary), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_BOLD, ExcelTheme.FMT_CURRENCY),
            (float(p.tax), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.nssf), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.other_deduction), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.total_deduction), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.net_salary), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
            (p.get_status_display(), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_BOLD, None),
        ]
        zebra = ExcelTheme.ZEBRA_FILL if r_idx % 2 == 0 else PatternFill(fill_type=None)
        for c_idx, (v, align, font, fmt) in enumerate(row_vals, start=1):
            cell = ws2.cell(row=r_idx, column=c_idx, value=v)
            cell.font = font
            cell.alignment = align
            cell.border = ExcelTheme.BORDER_THIN
            cell.fill = zebra
            if fmt:
                cell.number_format = fmt

    ws2.freeze_panes = 'A6'
    auto_fit_columns(ws2)

    # Sheet 3: Attendance Ledger
    ws3 = wb.create_sheet(title="Attendance Ledger")
    ws3.views.sheetView[0].showGridLines = True

    add_excel_header_block(
        ws3,
        company_name=company_name,
        report_title="Attendance & Time Logs",
        subtitle=f"Total Records: {len(attendances)}",
        generated_by=generated_by,
        max_col=8
    )

    att_headers = ["#", "Date", "Employee Code", "Employee Name", "Department", "Check In", "Check Out", "Working Hours", "Status"]
    ws3.row_dimensions[5].height = 24

    for c_idx, h in enumerate(att_headers, start=1):
        c = ws3.cell(row=5, column=c_idx, value=h)
        c.font = ExcelTheme.FONT_HEADER
        c.fill = ExcelTheme.NAVY_HEADER_FILL
        c.alignment = ExcelTheme.ALIGN_HEADER
        c.border = ExcelTheme.BORDER_THIN

    for r_idx, a in enumerate(attendances, start=6):
        emp = a.employee
        cin = a.check_in.strftime("%H:%M") if a.check_in else "-"
        cout = a.check_out.strftime("%H:%M") if a.check_out else "-"
        hours_str = str(a.working_hours).split('.')[0] if a.working_hours else "-"

        ws3.row_dimensions[r_idx].height = 20
        row_vals = [
            (r_idx - 5, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (a.date.strftime("%Y-%m-%d"), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (emp.employee_code, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (f"{emp.first_name} {emp.last_name}".strip(), ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_BOLD, None),
            (emp.department.name if emp.department else "-", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_REGULAR, None),
            (cin, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (cout, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (hours_str, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (a.get_status_display(), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_BOLD, None),
        ]
        zebra = ExcelTheme.ZEBRA_FILL if r_idx % 2 == 0 else PatternFill(fill_type=None)
        for c_idx, (v, align, font, fmt) in enumerate(row_vals, start=1):
            cell = ws3.cell(row=r_idx, column=c_idx, value=v)
            cell.font = font
            cell.alignment = align
            cell.border = ExcelTheme.BORDER_THIN
            cell.fill = zebra
            if fmt:
                cell.number_format = fmt

    ws3.freeze_panes = 'A6'
    auto_fit_columns(ws3)

    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()


def generate_detail_report_pdf(category, data_list, company_name="Payroll MGM", generated_by="Admin"):
    """Generates a landscape, multi-column detailed ledger PDF."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(letter),
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=45
    )

    styles = get_pdf_styles()
    story = []

    title_map = {
        'employees': "Employee Master Roster Ledger",
        'payroll': "Payroll Register Master Ledger",
        'attendance': "Attendance & Timesheet Ledger"
    }

    report_title = title_map.get(category, "Detailed Ledger Report")
    story.append(Paragraph(html.escape(company_name.upper()), styles['CompanyName']))
    story.append(Paragraph(report_title, styles['ReportTitle']))
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    story.append(Paragraph(f"Category: <b>{category.title()}</b> &nbsp;|&nbsp; Records: {len(data_list)} &nbsp;|&nbsp; Generated: {now_str} &nbsp;|&nbsp; By: {html.escape(generated_by)}", styles['ReportSubtitle']))

    if category == 'payroll':
        headers = ["#", "Period", "Code", "Employee Name", "Department", "Basic", "Allow.", "OT", "Gross", "Tax", "Deduct.", "Net Salary", "Status"]
        col_w = [25, 45, 45, 120, 80, 50, 45, 40, 55, 45, 50, 65, 55]
        t_data = [[Paragraph(h, styles['TableHeaderRight'] if h in ["Basic", "Allow.", "OT", "Gross", "Tax", "Deduct.", "Net Salary"] else styles['TableHeader']) for h in headers]]

        for idx, p in enumerate(data_list, start=1):
            emp = p.employee
            t_data.append([
                Paragraph(str(idx), styles['TableCellCenter']),
                Paragraph(p.payroll_period.strftime("%b %y"), styles['TableCellCenter']),
                Paragraph(html.escape(emp.employee_code), styles['TableCell']),
                Paragraph(f"<b>{html.escape(emp.first_name)} {html.escape(emp.last_name)}</b>", styles['TableCell']),
                Paragraph(html.escape(emp.department.name if emp.department else "-"), styles['TableCell']),
                Paragraph(f"${p.basic_salary:,.0f}", styles['TableCellRight']),
                Paragraph(f"${p.allowance:,.0f}", styles['TableCellRight']),
                Paragraph(f"${p.overtime:,.0f}", styles['TableCellRight']),
                Paragraph(f"<b>${p.gross_salary:,.0f}</b>", styles['TableCellRightBold']),
                Paragraph(f"${p.tax:,.0f}", styles['TableCellRight']),
                Paragraph(f"-${p.total_deduction:,.0f}", styles['TableCellRight']),
                Paragraph(f"<b>${p.net_salary:,.0f}</b>", styles['TableCellRightBold']),
                Paragraph(html.escape(p.get_status_display()), styles['TableCellCenter']),
            ])
    elif category == 'attendance':
        headers = ["#", "Date", "Code", "Employee Name", "Department", "Check In", "Check Out", "Hours", "Status"]
        col_w = [30, 70, 60, 180, 130, 70, 70, 50, 60]
        t_data = [[Paragraph(h, styles['TableHeader']) for h in headers]]

        for idx, a in enumerate(data_list, start=1):
            emp = a.employee
            cin = a.check_in.strftime("%H:%M") if a.check_in else "-"
            cout = a.check_out.strftime("%H:%M") if a.check_out else "-"
            hours_str = str(a.working_hours).split('.')[0] if a.working_hours else "-"
            t_data.append([
                Paragraph(str(idx), styles['TableCellCenter']),
                Paragraph(a.date.strftime("%Y-%m-%d"), styles['TableCellCenter']),
                Paragraph(html.escape(emp.employee_code), styles['TableCell']),
                Paragraph(f"<b>{html.escape(emp.first_name)} {html.escape(emp.last_name)}</b>", styles['TableCell']),
                Paragraph(html.escape(emp.department.name if emp.department else "-"), styles['TableCell']),
                Paragraph(cin, styles['TableCellCenter']),
                Paragraph(cout, styles['TableCellCenter']),
                Paragraph(hours_str, styles['TableCellCenter']),
                Paragraph(html.escape(a.get_status_display()), styles['TableCellCenter']),
            ])
    else:  # Employees
        headers = ["#", "Code", "Employee Name", "Gender", "Email", "Phone", "Department", "Position", "Basic Salary", "Status"]
        col_w = [30, 60, 140, 45, 120, 75, 80, 80, 55, 45]
        t_data = [[Paragraph(h, styles['TableHeaderRight'] if h == "Basic Salary" else styles['TableHeader']) for h in headers]]

        for idx, emp in enumerate(data_list, start=1):
            t_data.append([
                Paragraph(str(idx), styles['TableCellCenter']),
                Paragraph(html.escape(emp.employee_code), styles['TableCell']),
                Paragraph(f"<b>{html.escape(emp.first_name)} {html.escape(emp.last_name)}</b>", styles['TableCellBold']),
                Paragraph(emp.get_gender_display()[:1], styles['TableCellCenter']),
                Paragraph(html.escape(emp.email), styles['TableCell']),
                Paragraph(html.escape(emp.phone or "-"), styles['TableCell']),
                Paragraph(html.escape(emp.department.name if emp.department else "-"), styles['TableCell']),
                Paragraph(html.escape(emp.position.name if emp.position else "-"), styles['TableCell']),
                Paragraph(f"<b>${emp.basic_salary:,.0f}</b>", styles['TableCellRightBold']),
                Paragraph(html.escape(emp.get_status_display()), styles['TableCellCenter']),
            ])

    if len(t_data) == 1:
        t_data.append([Paragraph("No records found.", styles['TableCellCenter'])] + [""] * (len(headers) - 1))

    t = Table(t_data, colWidths=col_w, repeatRows=1)
    t_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 3.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3.5),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]
    if len(t_data) == 2 and not data_list:
        t_style.append(('SPAN', (0, 1), (-1, 1)))

    t.setStyle(TableStyle(t_style))
    story.append(t)
    story.append(build_signature_block(page_width=720))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()


# ==============================================================================
# 4. OFFICIAL PAYSLIP PDF
# ==============================================================================

def generate_payslip_pdf(payroll, company=None):
    """Generates an executive, official salary payslip voucher in PDF."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = get_pdf_styles()
    story = []

    emp = payroll.employee
    company_obj = company or getattr(emp, 'company', None)
    company_name = company_obj.name if company_obj else "Payroll MGM Inc"
    company_addr = getattr(company_obj, 'address', '') if company_obj else ""
    company_phone = getattr(company_obj, 'phone', '') if company_obj else ""
    company_email = getattr(company_obj, 'email', '') if company_obj else ""

    # Corporate Header Box
    header_cell = [
        Paragraph(f"<b><font size=16 color='#1E3A8A'>{html.escape(company_name.upper())}</font></b>", styles['TableCellCenter']),
        Paragraph(f"<font color='#64748B'>{html.escape(company_addr or 'Corporate Headquarters')} {('• Tel: ' + company_phone) if company_phone else ''} {('• Email: ' + company_email) if company_email else ''}</font>", styles['TableCellCenter']),
        Spacer(1, 4),
        Paragraph("<font size=13 color='#0F172A'><b>CONFIDENTIAL SALARY PAYSLIP</b></font>", styles['TableCellCenter']),
        Paragraph(f"<font size=10 color='#2563EB'><b>Period: {payroll.payroll_period.strftime('%B %Y')}</b></font>", styles['TableCellCenter']),
    ]
    t_hdr = Table([[header_cell]], colWidths=[540])
    t_hdr.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#1E3A8A')),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(t_hdr)
    story.append(Spacer(1, 12))

    # 2-Column Employee & Payroll Metadata Card
    meta_table = [
        [
            Paragraph("<b>EMPLOYEE DETAILS</b>", styles['TableCellBold']),
            Paragraph("<b>PAYROLL SPECIFICATIONS</b>", styles['TableCellBold'])
        ],
        [
            Paragraph(f"Name: <b>{html.escape(emp.first_name)} {html.escape(emp.last_name)}</b>", styles['TableCell']),
            Paragraph(f"Slip Number: <b>PS-{payroll.id:06d}</b>", styles['TableCell'])
        ],
        [
            Paragraph(f"Employee ID: <b>{html.escape(emp.employee_code)}</b>", styles['TableCell']),
            Paragraph(f"Pay Period: <b>{payroll.payroll_period.strftime('%B %Y')}</b>", styles['TableCell'])
        ],
        [
            Paragraph(f"Department: <b>{html.escape(emp.department.name if emp.department else '-')}</b>", styles['TableCell']),
            Paragraph(f"Issue Date: <b>{payroll.created_at.strftime('%Y-%m-%d')}</b>", styles['TableCell'])
        ],
        [
            Paragraph(f"Designation: <b>{html.escape(emp.position.name if emp.position else '-')}</b>", styles['TableCell']),
            Paragraph(f"Payment Status: <b><font color='#059669'>{html.escape(payroll.get_status_display().upper())}</font></b>", styles['TableCell'])
        ]
    ]
    t_meta = Table(meta_table, colWidths=[270, 270])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#E2E8F0')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#F1F5F9')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(t_meta)
    story.append(Spacer(1, 14))

    # Earnings & Deductions Breakdown Table
    breakdown_data = [
        [
            Paragraph("EARNINGS", styles['TableHeader']),
            Paragraph("AMOUNT ($)", styles['TableHeaderRight']),
            Paragraph("DEDUCTIONS", styles['TableHeader']),
            Paragraph("AMOUNT ($)", styles['TableHeaderRight'])
        ],
        [
            Paragraph("Basic Salary", styles['TableCell']),
            Paragraph(f"${payroll.basic_salary:,.2f}", styles['TableCellRight']),
            Paragraph("Tax Withheld", styles['TableCell']),
            Paragraph(f"${payroll.tax:,.2f}", styles['TableCellRight'])
        ],
        [
            Paragraph("Allowances", styles['TableCell']),
            Paragraph(f"${payroll.allowance:,.2f}", styles['TableCellRight']),
            Paragraph("NSSF Contribution", styles['TableCell']),
            Paragraph(f"${payroll.nssf:,.2f}", styles['TableCellRight'])
        ],
        [
            Paragraph("Overtime Compensation", styles['TableCell']),
            Paragraph(f"${payroll.overtime:,.2f}", styles['TableCellRight']),
            Paragraph("Other Statutory Deductions", styles['TableCell']),
            Paragraph(f"${payroll.other_deduction:,.2f}", styles['TableCellRight'])
        ],
        [
            Paragraph("Bonus / Incentive Bonus", styles['TableCell']),
            Paragraph(f"${payroll.bonus:,.2f}", styles['TableCellRight']),
            Paragraph("-", styles['TableCell']),
            Paragraph("-", styles['TableCellRight'])
        ],
        [
            Paragraph("<b>TOTAL GROSS EARNINGS</b>", styles['TableCellBold']),
            Paragraph(f"<b>${payroll.gross_salary:,.2f}</b>", styles['TableCellRightBold']),
            Paragraph("<b>TOTAL DEDUCTIONS</b>", styles['TableCellBold']),
            Paragraph(f"<font color='#DC2626'><b>-${payroll.total_deduction:,.2f}</b></font>", styles['TableCellRightBold'])
        ]
    ]

    t_break = Table(breakdown_data, colWidths=[170, 100, 170, 100])
    t_break.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#F1F5F9')),
        ('LINEABOVE', (0, -1), (-1, -1), 1, colors.HexColor('#0F172A')),
        ('LINEBELOW', (0, -1), (-1, -1), 1, colors.HexColor('#0F172A')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(t_break)
    story.append(Spacer(1, 14))

    # Prominent Net Pay Banner
    net_cell = [
        Paragraph("<font size=10 color='#FFFFFF'><b>NET TAKE-HOME REMUNERATION:</b></font>", styles['TableCellCenter']),
        Spacer(1, 2),
        Paragraph(f"<font size=20 color='#FFFFFF'><b>${payroll.net_salary:,.2f}</b></font>", styles['TableCellCenter']),
    ]
    t_net = Table([[net_cell]], colWidths=[540])
    t_net.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#1E3A8A')),
        ('BOX', (0, 0), (-1, -1), 1.5, colors.HexColor('#0F172A')),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(t_net)
    story.append(Spacer(1, 10))

    # Footer note
    note = Paragraph("<font size=7.5 color='#64748B'><i>Note: This computer-generated payslip is an official document of Payroll MGM. All taxes and contributions have been processed according to legal statutory obligations. For discrepancies, contact the HR department within 5 business days.</i></font>", styles['TableCellCenter'])
    story.append(note)

    # Signatures
    story.append(build_signature_block(page_width=540))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()


# ==============================================================================
# 5. GENERIC ATTENDANCE & PAYROLL LIST EXPORTERS
# ==============================================================================

def generate_attendance_list_excel(attendances, company_name="Payroll MGM", generated_by="Admin"):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Attendance Records"
    ws.views.sheetView[0].showGridLines = True

    add_excel_header_block(
        ws,
        company_name=company_name,
        report_title="Company Attendance Records",
        subtitle=f"Total Records: {len(attendances)}",
        generated_by=generated_by,
        max_col=8
    )

    headers = ["#", "Date", "Employee Code", "Employee Name", "Department", "Check In", "Check Out", "Working Hours", "Status"]
    ws.row_dimensions[5].height = 24

    for c_idx, h in enumerate(headers, start=1):
        c = ws.cell(row=5, column=c_idx, value=h)
        c.font = ExcelTheme.FONT_HEADER
        c.fill = ExcelTheme.NAVY_HEADER_FILL
        c.alignment = ExcelTheme.ALIGN_HEADER
        c.border = ExcelTheme.BORDER_THIN

    for idx, a in enumerate(attendances, start=1):
        r_idx = 5 + idx
        emp = a.employee
        cin = a.check_in.strftime("%H:%M") if a.check_in else "-"
        cout = a.check_out.strftime("%H:%M") if a.check_out else "-"
        hours_str = str(a.working_hours).split('.')[0] if a.working_hours else "-"

        ws.row_dimensions[r_idx].height = 20
        row_vals = [
            (idx, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (a.date.strftime("%Y-%m-%d"), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (emp.employee_code, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (f"{emp.first_name} {emp.last_name}".strip(), ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_BOLD, None),
            (emp.department.name if emp.department else "-", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_REGULAR, None),
            (cin, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (cout, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (hours_str, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (a.get_status_display(), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_BOLD, None),
        ]
        zebra = ExcelTheme.ZEBRA_FILL if r_idx % 2 == 0 else PatternFill(fill_type=None)
        for c_idx, (v, align, font, fmt) in enumerate(row_vals, start=1):
            cell = ws.cell(row=r_idx, column=c_idx, value=v)
            cell.font = font
            cell.alignment = align
            cell.border = ExcelTheme.BORDER_THIN
            cell.fill = zebra
            if fmt:
                cell.number_format = fmt

    ws.freeze_panes = 'A6'
    auto_fit_columns(ws)

    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()


def generate_payroll_list_excel(payrolls, company_name="Payroll MGM", generated_by="Admin"):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Payroll Records"
    ws.views.sheetView[0].showGridLines = True

    add_excel_header_block(
        ws,
        company_name=company_name,
        report_title="Company Payroll Records",
        subtitle=f"Total Records: {len(payrolls)}",
        generated_by=generated_by,
        max_col=10
    )

    headers = ["#", "Period", "Employee Code", "Employee Name", "Department", "Basic Salary", "Gross Salary", "Total Deductions", "Net Salary", "Status"]
    ws.row_dimensions[5].height = 24

    for c_idx, h in enumerate(headers, start=1):
        c = ws.cell(row=5, column=c_idx, value=h)
        c.font = ExcelTheme.FONT_HEADER
        c.fill = ExcelTheme.NAVY_HEADER_FILL
        c.alignment = ExcelTheme.ALIGN_HEADER
        c.border = ExcelTheme.BORDER_THIN

    for idx, p in enumerate(payrolls, start=1):
        r_idx = 5 + idx
        emp = p.employee
        ws.row_dimensions[r_idx].height = 20
        row_vals = [
            (idx, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (p.payroll_period.strftime("%b %Y"), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (emp.employee_code, ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_REGULAR, None),
            (f"{emp.first_name} {emp.last_name}".strip(), ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_BOLD, None),
            (emp.department.name if emp.department else "-", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_REGULAR, None),
            (float(p.basic_salary), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.gross_salary), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.total_deduction), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_REGULAR, ExcelTheme.FMT_CURRENCY),
            (float(p.net_salary), ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_BOLD, ExcelTheme.FMT_CURRENCY),
            (p.get_status_display(), ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_BOLD, None),
        ]
        zebra = ExcelTheme.ZEBRA_FILL if r_idx % 2 == 0 else PatternFill(fill_type=None)
        for c_idx, (v, align, font, fmt) in enumerate(row_vals, start=1):
            cell = ws.cell(row=r_idx, column=c_idx, value=v)
            cell.font = font
            cell.alignment = align
            cell.border = ExcelTheme.BORDER_THIN
            cell.fill = zebra
            if fmt:
                cell.number_format = fmt

    if payrolls:
        last_r = 5 + len(payrolls) + 1
        ws.row_dimensions[last_r].height = 22
        tots = [
            ("Grand Total", ExcelTheme.ALIGN_LEFT, ExcelTheme.FONT_TOTAL, None),
            ("", ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_TOTAL, None),
            ("", ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_TOTAL, None),
            ("", ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_TOTAL, None),
            ("", ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_TOTAL, None),
            (f"=SUM(F6:F{last_r-1})", ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
            (f"=SUM(G6:G{last_r-1})", ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
            (f"=SUM(H6:H{last_r-1})", ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
            (f"=SUM(I6:I{last_r-1})", ExcelTheme.ALIGN_RIGHT, ExcelTheme.FONT_TOTAL, ExcelTheme.FMT_CURRENCY),
            ("", ExcelTheme.ALIGN_CENTER, ExcelTheme.FONT_TOTAL, None),
        ]
        for c_idx, (v, align, font, fmt) in enumerate(tots, start=1):
            cell = ws.cell(row=last_r, column=c_idx, value=v)
            cell.font = font
            cell.alignment = align
            cell.border = ExcelTheme.BORDER_TOTAL
            cell.fill = ExcelTheme.TOTALS_FILL
            if fmt:
                cell.number_format = fmt

    ws.freeze_panes = 'A6'
    auto_fit_columns(ws)

    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()
