# Generated by Django 5.1 on 2026-09-03 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0002_employee_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('flexible', 'Flexible'), ('standard', 'Standard')], default='flexible', max_length=20)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_half_day', models.BooleanField(default=False)),
                ('is_work_day', models.BooleanField(default=True)),
                ('shift_label', models.CharField(default='No Work Time 2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_schedules', to='employees.employee')),
            ],
            options={
                'ordering': ['employee', 'day_of_week'],
                'unique_together': {('employee', 'day_of_week')},
            },
        ),
    ]
