# Generated by Django 5.1 on 2026-09-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employeeschedule'),
        ('employees', '0002_employee_branch'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeschedule',
            index=models.Index(fields=['employee', 'day_of_week'], name='attendance__employe_242e21_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeschedule',
            index=models.Index(fields=['is_work_day'], name='attendance__is_work_6802fb_idx'),
        ),
    ]
