# Generated by Django 5.1 on 2026-09-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_employeeschedule_attendance__employe_242e21_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeschedule',
            name='end_time2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeschedule',
            name='start_time2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='shift_label',
            field=models.CharField(default='Full Day', max_length=100),
        ),
    ]
