# Generated by Django 6.0.8 on 2026-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employeeschedule_end_time2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('early_leave', 'Early Leave'), ('checkout_early', 'Checkout Early'), ('overtime', 'Overtime')], default='present', max_length=20),
        ),
    ]
