# Generated by Django 6.0.8 on 2026-09-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('checkout_early', 'Checkout Early'), ('overtime', 'Overtime')], default='present', max_length=20),
        ),
    ]
