# Generated by Django 6.0.8 on 2026-09-19 13:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_status'),
        ('companies', '0005_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lunch Break', max_length=100)),
                ('break_type', models.CharField(choices=[('lunch', 'Lunch Break'), ('tea', 'Tea Break'), ('custom', 'Custom Break')], default='lunch', max_length=20)),
                ('start_time', models.TimeField(default=datetime.time(12, 0), help_text='Start time of the break, e.g. 12:00')),
                ('end_time', models.TimeField(default=datetime.time(13, 0), help_text='End time of the break, e.g. 13:00')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration in minutes (e.g. 60 for 1 hour)')),
                ('auto_deduct', models.BooleanField(default=True, help_text='Automatically deduct this break from working hours if shift overlaps')),
                ('min_work_hours', models.DecimalField(decimal_places=2, default=4.0, help_text='Minimum elapsed hours worked to qualify for break deduction', max_digits=4)),
                ('status', models.BooleanField(default=True, help_text='Active / Inactive status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Optional company assignment. If blank, applies to all companies.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch_breaks', to='companies.company')),
            ],
            options={
                'verbose_name': 'Lunch Break',
                'verbose_name_plural': 'Lunch Breaks',
                'ordering': ['start_time', 'name'],
            },
        ),
    ]
