# Generated by Django 6.0.8 on 2026-09-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leavebalance_allocated_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveperiod',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveperiod',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
