# Generated by Django 5.1 on 2026-09-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_branch'),
        ('employees', '0003_remove_employee_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
