# Generated by Django 5.1 on 2026-09-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch',
        ),
    ]
